name: Monitor Ranking MuHolyShit

on:
  schedule:
    - cron: '*/15 * * * *'  # Executa a cada 15 minutos
  workflow_dispatch:        # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install chromium

      - name: Executar Robô
        run: python main.py
